### ISSUE TITLE
Tx has been overridden by another transaction with the same nonce, which means it has failed

### ISSUE THREAD

**Issue by JohnAllen** [makerdao/arbitrage-keeper#6]
``` WARNING  Transaction ERC20Token('0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359').approve(['0xbda109309f9fafa6dd6a9cb9f1df4085b27ee8ef', 115792089237316195423570985008687907853269984665640564039457584007913129639935]) has been overridden by another transaction with the same nonce, which means it has failed```

Can someone help me understand what's going on here?  I started this keeper and it sent a bunch of approval transactions, which were confirmed.

Seems like it's worried about something that it shouldn't be anymore.

And while you're here, what is the `base-token`? I used weth but think I may be missing something.

**Comment by JohnAllen** [comment]
Solution was to just keep doing this.  Eventually this error went away.

**Comment by reverendus** [comment]
The `Transaction (...) has been overridden by another transaction with the same nonce, which means it has failed` warning sometimes get displayed if the keeper notices that the account nonce (`getTransactionCount`) got incremented, but the receipt couldn't be fetched. Normally it happens when some other transaction will get mined with the same nonce, but it's also possible for it to happen due to chain reorgs for example... This is what probably happened in your case. I wouldn't worry too much about it as long as you know you are not running any other bots on the same account.

**Comment by reverendus** [comment]
Regarding _base token_, it's the token that the `arbitrage-keeper` will try to accumulate as a result of the arbitrage transactions it performs. If you set it to DAI (DAI's ERC20 token address in fact), you should give the bot some DAI and then expect it to earn more if it in the long run.
